export const DEFAULT_ORGANIZATIONS = [
  "A Cloud Guru",
  "ACCA",
  "Adobe",
  "Amazon Web Services (AWS)",
  "ASQ",
  "Atlassian",
  "AXELOS (PRINCE2 / ITIL)",
  "BCS (British Computer Society)",
  "Canva",
  "CFA Institute",
  "Chartered Institute of Marketing",
  "Cisco",
  "CompTIA",
  "Coursera",
  "Credly",
  "Databricks",
  "Docker",
  "EC-Council",
  "edX",
  "Figma",
  "Fortinet",
  "GitHub",
  "GitLab",
  "Google",
  "HashiCorp",
  "Holopin",
  "HRCI",
  "HubSpot Academy",
  "IBM",
  "ISACA",
  "ISC2",
  "Kubernetes (CNCF)",
  "LinkedIn Learning",
  "Linux Foundation",
  "Meta",
  "Microsoft",
  "Oracle",
  "Palo Alto Networks",
  "PeopleCert",
  "Pluralsight",
  "PMI (Project Management Institute)",
  "Salesforce",
  "Scrum Alliance",
  "SHRM",
  "Six Sigma Council",
  "Sketch",
  "Snowflake",
  "Splunk",
  "Tableau",
  "Udemy",
  "Unity",
  "Unreal Engine (Epic Games)",
] as const;
